### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by timscott** [Odinvt/react-native-lanscan#1]
Trying to install `react-native-lanscan` got this:

``` bash
> npm i -S react-native-lanscan

> react-native-lanscan@1.0.2 postinstall /[redacted]/node_modules/react-native-lanscan
> babel main.js --out-file main-tf.js

SyntaxError: main.js: Unexpected token (9:25)
   7 | export class LANScan extends EventEmitter {
   8 |
>  9 |     static listenerCount = 0;
     |                          ^
  10 |
  11 |     _connectedHosts;
  12 |     _availableHosts;
```

I guess this where it happens: https://github.com/Odinvt/react-native-lanscan/blob/master/package.json#L7

Maybe needs a preset of at least stage-2?

**Comment by Odinvt** [comment]
Fixed in ['d29dfc3'](https://github.com/Odinvt/react-native-lanscan/commit/d29dfc3e21f339a89187f4e2f1add6594e9e91a8). Needed the correct babel presets. Now on version 1.0.3 on NPM. Thank you for your contribution :)
